spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
    application:
      name: microservicecloud-config-wrp-dev  
---
spring:
  profiles: test
    application:
      name: microservicecloud-config-wrp-test 